const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {PGlite}=require('@electric-sql/pglite'),{pgcrypto}=require('@electric-sql/pglite/contrib/pgcrypto');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8').replace(/\r\n/g,'\n');
(async()=>{const db=new PGlite({extensions:{pgcrypto}});try{
 const fixture=read('tests/fresh-install-readiness.cjs'),start=fixture.lastIndexOf('await db.exec(`',fixture.indexOf('create role anon'))+15,end=fixture.indexOf('`);',start);
 await db.exec(Function('return `'+fixture.slice(start,end)+'`;')());
 await db.exec(read('schema_consolidated_fresh_install.sql'));
 const q=async(sql,args=[])=> (await db.query(sql,args)).rows[0].r;
 const before=(await db.query("select md5(pg_get_functiondef('manual_employee_check(text,text,text)'::regprocedure)) hash")).rows[0].hash;
 await db.exec("create or replace function public.is_super_admin() returns boolean language sql as $$select current_setting('test.super',true)='yes'$$;set test.super='yes'");
 assert((await q("select admin_save_guard(null,'','9988776611','0799999911',true) r")).ok);
 assert((await q("select admin_save_guard(null,'','9988776622','0799999922',true) r")).ok,'multiple guards without names');
 assert((await q("select admin_save_guard(null,'Same name','9988776633','0799999933',true) r")).ok);
 assert((await q("select admin_save_guard(null,'Same name','9988776644','0799999944',true) r")).ok,'names need not be unique');
 await db.exec('set role anon');
 await assert.rejects(db.query('select * from private.guard_profiles'),/permission denied/);
 await assert.rejects(db.query("insert into private.guard_profiles(guard_id) values(gen_random_uuid())"),/permission denied/);
 assert.equal((await q("select guard_login('Same name','0799999933') r")).ok,false,'name cannot log in');
 const a=await q("select guard_login('٩٩٨٨٧٧٦٦١١','0799999911') r"),b=await q("select guard_login('9988776622','0799999922') r");assert(a.ok&&b.ok);
 assert.equal((await q("select guard_get_profile('bad') r")).error,'AUTH_REQUIRED');
 const save=async(token,profile)=>q('select guard_save_profile($1,$2) r',[token,JSON.stringify(profile)]);
 assert((await save(a.token,{full_name:'',age:null,residence:'',about:''})).ok);
 assert((await save(a.token,{full_name:'Optional Name',age:45,residence:'Amman',about:'Official guard',photo_base64:'/9j/AA=='})).ok);
 const p=(await q('select guard_get_profile($1) r',[a.token])).profile;assert.equal(p.full_name,'Optional Name');assert.equal(p.age,45);assert.equal(p.residence,'Amman');assert(p.photo_base64);
 const other=(await q('select guard_get_profile($1) r',[b.token])).profile;assert.equal(other.national_id,'9988776622');assert.equal(other.photo_base64,null);
 assert((await save(a.token,{full_name:'',residence:'',about:'',national_id:'9988776622',guard_id:'00000000-0000-0000-0000-000000000000'})).ok);
 assert.equal((await q('select guard_get_profile($1) r',[a.token])).profile.national_id,'9988776611','cannot change own identity');
 assert((await q('select guard_get_profile($1) r',[a.token])).profile.photo_base64,'ordinary update retains image');
 for(const bad of [{age:200},{age:'bad'},{residence:'x'.repeat(201)},{about:'x'.repeat(1001)},{photo_base64:'a'.repeat(262145)},{photo_base64:'PGh0bWw+'},{photo_base64:'%%%'}]) assert.equal((await save(a.token,bad)).ok,false);
 assert((await save(a.token,{remove_photo:true})).ok);assert.equal((await q('select guard_get_profile($1) r',[a.token])).profile.photo_base64,null);
 await db.exec('reset role');
 const guard=(await q('select admin_list_guards() r')).guards.find(g=>g.national_id==='9988776611');
 assert((await q('select admin_save_guard($1,$2,$3,$4,false) r',[guard.id,'',guard.national_id,''])).ok);
 assert.equal((await q('select guard_get_profile($1) r',[a.token])).error,'AUTH_REQUIRED');assert.equal((await save(a.token,{})).error,'AUTH_REQUIRED');
 assert.equal((await db.query("select md5(pg_get_functiondef('manual_employee_check(text,text,text)'::regprocedure)) hash")).rows[0].hash,before);
 assert.equal((await db.query("select count(*) n from admin_audit_logs where action='GUARD_UPDATE_OWN_PROFILE'")).rows[0].n,4);
 console.log('PASS national-ID-only guard login, optional/nonunique name, isolated private profiles, optional photo preserve/remove, input bounds, identity immutability, audit and revoked sessions');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
